name: tiktok-harvester
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=22.0.0
  - pandas>=1.4.0
  - numpy>=1.22.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.2
  - streamlit>=1.10.0
  - selenium>=4.1.0
  - webdriver-manager>=3.5.0
  - pip:
    - plotly>=5.7.0
    - altair>=4.2.0
    - openpyxl>=3.0.9
    - xlsxwriter>=3.0.2
    - rich>=12.0.0
    - python-dotenv>=0.20.0
    - beautifulsoup4>=4.11.0
    - fake-useragent>=0.1.11